import React, { createContext, useContext, useState } from 'react';

const translations = {
  he: {
    dir: 'rtl',
    navbar: {
      brand: '🥗 מערכת תזונה חכמה',
      dashboard: 'דשבורד',
      settings: 'הגדרות',
      hello: 'שלום',
      logout: 'התנתקות',
    },
    footer: {
      name: 'מערכת תכנון תזונה חכמה',
      year: '2025',
      slogan: 'אכול נכון, חי טוב',
    },
    login: {
      title: 'מערכת תזונה חכמה',
      subtitle: 'התחבר או הירשם — אותו טופס, פשוט יותר',
      registerNote: 'משתמש חדש? הכנס מייל וסיסמה ונבנה לך פרופיל תזונה אישי',
      emailLabel: 'אימייל',
      emailPlaceholder: 'your@email.com',
      passwordLabel: 'סיסמה',
      passwordPlaceholder: 'לפחות 6 תווים',
      submit: 'התחבר / הירשם',
      loading: 'מתחבר...',
      hint: 'לדוגמה: maya@example.com / 123456',
      errEmail: 'נדרשת כתובת מייל תקינה',
      errPassword: 'הסיסמה חייבת להכיל לפחות 6 תווים',
      errWrongPassword: 'הסיסמה שגויה',
    },
    dashboard: {
      qTitle: 'בואו נבנה לך תפריט אישי',
      qSubtitle: 'מלא את הפרטים האישיים שלך כדי לקבל תפריט יומי מותאם',
      ageLabel: 'גיל',
      weightLabel: 'משקל (ק"ג)',
      heightLabel: 'גובה (ס"מ)',
      goalLabel: 'מטרה',
      goals: { loss: 'ירידה במשקל', gain: 'עלייה במסה', health: 'חיים בריאים' },
      allergiesTitle: 'אלרגיות',
      allergiesSubtitle: 'סמן את כל האלרגיות הרלוונטיות',
      allergens: {
        eggs: 'ביצים', dairy: 'מוצרי חלב', gluten: 'גלוטן',
        fish: 'דגים', nuts: 'אגוזים', soy: 'סויה',
      },
      preferencesTitle: 'העדפות תזונתיות',
      vegetarianOnly: 'צמחוני בלבד',
      submit: 'צור תפריט יומי ➤',
      menuTitle: 'התפריט היומי שלך',
      caloriesInfo: 'יעד קלורי',
      calories: 'קלוריות',
      recalc: 'חשב מחדש',
      tableTitle: 'מתכונים מתאימים עבורך',
      loading: 'טוען מתכונים...',
      fetchError: 'שגיאה בטעינת המתכונים מהשרת',
      noRecipes: 'לא נמצאו מתכונים מתאימים',
      noRecipeForMeal: 'לא נמצא מתכון מתאים לארוחה זו לפי ההעדפות שלך',
      profileAllergies: 'אלרגיות',
      profilePrefs: 'העדפות',
      none: 'ללא',
      errAge: 'גיל חייב להיות בין 10 ל-120',
      errWeight: 'משקל חייב להיות בין 20 ל-300 ק"ג',
      errHeight: 'גובה חייב להיות בין 100 ל-250 ס"מ',
    },
    table: {
      name: 'שם המתכון',
      mealType: 'ארוחה',
      calories: 'קלוריות',
      protein: 'חלבון (g)',
      carbs: 'פחמימות (g)',
      fat: 'שומן (g)',
      vegetarian: 'צמחוני',
      mealTypes: { breakfast: 'בוקר', lunch: 'צהריים', dinner: 'ערב' },
      empty: 'אין נתונים להצגה',
      swapLabel: 'החלף',
      currentMeal: '✓ נוכחי',
      swapTo: { breakfast: 'שנה לבוקר', lunch: 'שנה לצהריים', dinner: 'שנה לערב' },
    },
    card: {
      mealTypes: { breakfast: 'ארוחת בוקר', lunch: 'ארוחת צהריים', dinner: 'ארוחת ערב' },
      veg: '🌱 צמחוני',
      calories: 'קלוריות',
      protein: 'חלבון',
      carbs: 'פחמימות',
      fat: 'שומן',
      prepTime: "זמן הכנה",
      prepUnit: "דק'",
    },
    modal: {
      ingredients: 'מצרכים',
      instructions: 'הוראות הכנה',
      close: 'סגור',
      prepTime: "זמן הכנה",
      prepUnit: "דק'",
      calories: 'קלוריות',
      protein: 'חלבון',
      carbs: 'פחמימות',
      fat: 'שומן',
      veg: '🌱 צמחוני',
      allergens: 'אלרגנים',
    },
    settings: {
      title: 'הגדרות',
      displayNameLabel: 'שם תצוגה',
      languageLabel: 'שפה',
      notificationsLabel: 'קבל התראות במייל',
      save: 'שמור שינויים',
      saving: 'שומר...',
      success: 'ההגדרות נשמרו בהצלחה',
      errLoad: 'שגיאה בטעינת ההגדרות',
      errSave: 'שגיאה בשמירת ההגדרות',
      errDisplayName: 'שם תצוגה הוא שדה חובה',
      loading: 'טוען הגדרות...',
      langHe: 'עברית',
      langEn: 'English',
      accountTitle: 'פרטי חשבון',
      emailLabel: 'אימייל',
      newPasswordLabel: 'סיסמה חדשה',
      newPasswordPlaceholder: 'השאר ריק אם אינך רוצה לשנות',
      confirmPasswordLabel: 'אימות סיסמה',
      saveAccount: 'עדכן פרטי חשבון',
      savingAccount: 'מעדכן...',
      accountSuccess: 'פרטי החשבון עודכנו בהצלחה',
      errEmail: 'נדרשת כתובת מייל תקינה',
      errPassword: 'הסיסמה חייבת להכיל לפחות 6 תווים',
      errPasswordMatch: 'הסיסמאות אינן תואמות',
      errAccountSave: 'שגיאה בעדכון פרטי החשבון',
    },
  },
  en: {
    dir: 'ltr',
    navbar: {
      brand: '🥗 Smart Nutrition System',
      dashboard: 'Dashboard',
      settings: 'Settings',
      hello: 'Hello',
      logout: 'Logout',
    },
    footer: {
      name: 'Smart Nutrition Planning System',
      year: '2025',
      slogan: 'Eat right, live well',
    },
    login: {
      title: 'Smart Nutrition System',
      subtitle: 'Sign in or Register — one simple form',
      registerNote: "New user? Enter any email and password and we'll build your personal nutrition profile",
      emailLabel: 'Email',
      emailPlaceholder: 'your@email.com',
      passwordLabel: 'Password',
      passwordPlaceholder: 'At least 6 characters',
      submit: 'Sign In / Register',
      loading: 'Signing in...',
      hint: 'Example: maya@example.com / 123456',
      errEmail: 'A valid email address is required',
      errPassword: 'Password must be at least 6 characters',
      errWrongPassword: 'Incorrect password',
    },
    dashboard: {
      qTitle: "Let's build your personal menu",
      qSubtitle: 'Fill in your personal details to get a customized daily menu',
      ageLabel: 'Age',
      weightLabel: 'Weight (kg)',
      heightLabel: 'Height (cm)',
      goalLabel: 'Goal',
      goals: { loss: 'Weight Loss', gain: 'Muscle Gain', health: 'Healthy Living' },
      allergiesTitle: 'Allergies',
      allergiesSubtitle: 'Check all that apply',
      allergens: {
        eggs: 'Eggs', dairy: 'Dairy', gluten: 'Gluten',
        fish: 'Fish', nuts: 'Nuts', soy: 'Soy',
      },
      preferencesTitle: 'Dietary Preferences',
      vegetarianOnly: 'Vegetarian only',
      submit: 'Create Daily Menu ➤',
      menuTitle: 'Your Daily Menu',
      caloriesInfo: 'Calorie Target',
      calories: 'calories',
      recalc: 'Recalculate',
      tableTitle: 'Recipes Suitable for You',
      loading: 'Loading recipes...',
      fetchError: 'Error loading recipes from server',
      noRecipes: 'No suitable recipes found',
      noRecipeForMeal: 'No suitable recipe found for this meal based on your preferences',
      profileAllergies: 'Allergies',
      profilePrefs: 'Preferences',
      none: 'None',
      errAge: 'Age must be between 10 and 120',
      errWeight: 'Weight must be between 20 and 300 kg',
      errHeight: 'Height must be between 100 and 250 cm',
    },
    table: {
      name: 'Recipe Name',
      mealType: 'Meal',
      calories: 'Calories',
      protein: 'Protein (g)',
      carbs: 'Carbs (g)',
      fat: 'Fat (g)',
      vegetarian: 'Vegetarian',
      mealTypes: { breakfast: 'Breakfast', lunch: 'Lunch', dinner: 'Dinner' },
      empty: 'No data to display',
      swapLabel: 'Swap',
      currentMeal: '✓ Current',
      swapTo: { breakfast: 'Use for Breakfast', lunch: 'Use for Lunch', dinner: 'Use for Dinner' },
    },
    card: {
      mealTypes: { breakfast: 'Breakfast', lunch: 'Lunch', dinner: 'Dinner' },
      veg: '🌱 Vegetarian',
      calories: 'Calories',
      protein: 'Protein',
      carbs: 'Carbs',
      fat: 'Fat',
      prepTime: 'Prep time',
      prepUnit: 'min',
    },
    modal: {
      ingredients: 'Ingredients',
      instructions: 'Preparation Instructions',
      close: 'Close',
      prepTime: 'Prep time',
      prepUnit: 'min',
      calories: 'Calories',
      protein: 'Protein',
      carbs: 'Carbs',
      fat: 'Fat',
      veg: '🌱 Vegetarian',
      allergens: 'Allergens',
    },
    settings: {
      title: 'Settings',
      displayNameLabel: 'Display Name',
      languageLabel: 'Language',
      notificationsLabel: 'Receive email notifications',
      save: 'Save Changes',
      saving: 'Saving...',
      success: 'Settings saved successfully',
      errLoad: 'Error loading settings',
      errSave: 'Error saving settings',
      errDisplayName: 'Display name is required',
      loading: 'Loading settings...',
      langHe: 'עברית',
      langEn: 'English',
      accountTitle: 'Account Details',
      emailLabel: 'Email',
      newPasswordLabel: 'New Password',
      newPasswordPlaceholder: 'Leave blank to keep current password',
      confirmPasswordLabel: 'Confirm Password',
      saveAccount: 'Update Account',
      savingAccount: 'Updating...',
      accountSuccess: 'Account details updated successfully',
      errEmail: 'A valid email address is required',
      errPassword: 'Password must be at least 6 characters',
      errPasswordMatch: 'Passwords do not match',
      errAccountSave: 'Error updating account details',
    },
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const saved = localStorage.getItem('language') || 'he';
  const [lang, setLang] = useState(saved);

  function switchLanguage(newLang) {
    localStorage.setItem('language', newLang);
    setLang(newLang);
  }

  const t = translations[lang] || translations.he;

  return (
    <LanguageContext.Provider value={{ lang, switchLanguage, t }}>
      <div dir={t.dir}>{children}</div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
