import React, { createContext, useContext, useState } from 'react';

const translations = {
  he: {
    dir: 'rtl',
    navbar: {
      brand: '🥗 מערכת תזונה חכמה',
      dashboard: 'דשבורד',
      recipeManagement: 'ניהול מתכונים',
      settings: 'הגדרות',
      hello: 'שלום',
      logout: 'התנתקות',
    },
    footer: {
      name: 'מערכת תכנון תזונה חכמה',
      year: '2026',
      slogan: 'אכול נכון, חיה טוב',
    },
    login: {
      title: 'מערכת תזונה חכמה',
      subtitle: 'התחבר או הירשם — אותו טופס, פשוט יותר',
      registerNote: 'משתמש חדש? הכנס מייל וסיסמה ונבנה לך פרופיל תזונה אישי',
      emailLabel: 'אימייל',
      emailPlaceholder: 'your@email.com',
      passwordLabel: 'סיסמה',
      passwordPlaceholder: 'לפחות 6 תווים',
      submit: 'התחבר / הירשם',
      loading: 'מתחבר...',
      hint: 'לדוגמה: maya@example.com / 123456',
      errEmail: 'נדרשת כתובת מייל תקינה',
      errPassword: 'הסיסמה חייבת להכיל לפחות 6 תווים',
      errWrongPassword: 'הסיסמה שגויה',
    },
    dashboard: {
      qTitle: 'בואו נבנה לך תפריט אישי',
      qSubtitle: 'מלא את הפרטים האישיים שלך כדי לקבל תפריט יומי מותאם',
      ageLabel: 'גיל',
      weightLabel: 'משקל (ק"ג)',
      heightLabel: 'גובה (ס"מ)',
      goalLabel: 'מטרה',
      goals: { loss: 'ירידה במשקל', gain: 'עלייה במסה', health: 'חיים בריאים' },
      activityLabel: 'רמת פעילות גופנית',
      activityLevels: {
        sedentary: 'יושבני (ללא פעילות)',
        light: 'קל (1–3 ימים בשבוע)',
        moderate: 'בינוני (3–5 ימים בשבוע)',
        active: 'פעיל (6–7 ימים בשבוע)',
        very_active: 'פעיל מאוד (עבודה פיזית)',
      },
      allergiesTitle: 'אלרגיות',
      allergiesSubtitle: 'סמן את כל האלרגיות הרלוונטיות',
      allergens: {
        eggs: 'ביצים', dairy: 'מוצרי חלב', gluten: 'גלוטן',
        fish: 'דגים', nuts: 'אגוזים', soy: 'סויה',
      },
      preferencesTitle: 'העדפות תזונתיות',
      vegetarianOnly: 'צמחוני בלבד',
      submit: 'צור תפריט יומי ➤',
      menuTitle: 'התפריט היומי שלך',
      caloriesInfo: 'יעד קלורי',
      calories: 'קלוריות',
      recalc: 'חשב מחדש',
      saveMenu: 'שמור תפריט',
      menuSaved: 'התפריט נשמר!',
      tableTitle: 'מתכונים מתאימים עבורך',
      loading: 'טוען מתכונים...',
      fetchError: 'שגיאה בטעינת המתכונים מהשרת',
      noRecipes: 'לא נמצאו מתכונים מתאימים',
      noRecipeForMeal: 'לא נמצא מתכון מתאים לארוחה זו לפי ההעדפות שלך',
      profileAllergies: 'אלרגיות',
      profilePrefs: 'העדפות',
      none: 'ללא',
      menuError: 'לא נמצא תפריט מתאים. נסה לשנות את ההגדרות.',
      errAge: 'גיל חייב להיות בין 10 ל-120',
      errWeight: 'משקל חייב להיות בין 20 ל-300 ק"ג',
      errHeight: 'גובה חייב להיות בין 100 ל-250 ס"מ',
    },
    table: {
      name: 'שם המתכון',
      mealType: 'ארוחה',
      calories: 'קלוריות',
      protein: 'חלבון (g)',
      carbs: 'פחמימות (g)',
      fat: 'שומן (g)',
      vegetarian: 'צמחוני',
      mealTypes: { breakfast: 'בוקר', lunch: 'צהריים', dinner: 'ערב' },
      empty: 'אין נתונים להצגה',
      swapLabel: 'החלף',
      currentMeal: '✓ נוכחי',
      swapTo: { breakfast: 'שנה לבוקר', lunch: 'שנה לצהריים', dinner: 'שנה לערב' },
    },
    card: {
      mealTypes: { breakfast: 'ארוחת בוקר', lunch: 'ארוחת צהריים', dinner: 'ארוחת ערב' },
      veg: '🌱 צמחוני',
      calories: 'קלוריות',
      protein: 'חלבון',
      carbs: 'פחמימות',
      fat: 'שומן',
      prepTime: "זמן הכנה",
      prepUnit: "דק'",
    },
    modal: {
      ingredients: 'מצרכים',
      instructions: 'הוראות הכנה',
      close: 'סגור',
      prepTime: "זמן הכנה",
      prepUnit: "דק'",
      calories: 'קלוריות',
      protein: 'חלבון',
      carbs: 'פחמימות',
      fat: 'שומן',
      veg: '🌱 צמחוני',
      allergens: 'אלרגנים',
    },
    settings: {
      title: 'הגדרות',
      firstNameLabel: 'שם פרטי',
      lastNameLabel: 'שם משפחה',
      languageLabel: 'שפה',
      notificationsLabel: 'קבל התראות במייל',
      save: 'שמור שינויים',
      saving: 'שומר...',
      success: 'ההגדרות נשמרו בהצלחה',
      errLoad: 'שגיאה בטעינת ההגדרות',
      errSave: 'שגיאה בשמירת ההגדרות',
      errFirstName: 'שם פרטי הוא שדה חובה',
      loading: 'טוען הגדרות...',
      langHe: 'עברית',
      langEn: 'English',
      accountTitle: 'פרטי חשבון',
      emailLabel: 'אימייל',
      newPasswordLabel: 'סיסמה חדשה',
      newPasswordPlaceholder: 'השאר ריק אם אינך רוצה לשנות',
      confirmPasswordLabel: 'אימות סיסמה',
      saveAccount: 'עדכן פרטי חשבון',
      savingAccount: 'מעדכן...',
      accountSuccess: 'פרטי החשבון עודכנו בהצלחה',
      errEmail: 'נדרשת כתובת מייל תקינה',
      errPassword: 'הסיסמה חייבת להכיל לפחות 6 תווים',
      errPasswordMatch: 'הסיסמאות אינן תואמות',
      errAccountSave: 'שגיאה בעדכון פרטי החשבון',
    },
    admin: {
      title: 'דשבורד מנהל',
      loading: 'טוען משתמשים...',
      colId: '#',
      colName: 'שם',
      colEmail: 'אימייל',
      colRole: 'תפקיד',
      colActions: 'פעולות',
      deleteBtn: 'מחק',
      youBadge: 'אתה',
      roles: { user: 'משתמש', nutritionist: 'תזונאי', admin: 'מנהל' },
      errLoad: 'שגיאה בטעינת המשתמשים.',
      errUpdate: 'שגיאה בעדכון התפקיד.',
      errDelete: 'שגיאה במחיקת המשתמש.',
    },
    recipeManagement: {
      title: 'ניהול מתכונים',
      loading: 'טוען מתכונים...',
      fetchError: 'שגיאה בטעינת המתכונים',
      colName: 'שם המתכון',
      colMealType: 'סוג ארוחה',
      colCalories: 'קלוריות',
      colProtein: "חלבון (ג')",
      colCarbs: "פחמימות (ג')",
      colFat: "שומן (ג')",
      colActions: 'פעולות',
      editBtn: 'ערוך',
      deleteBtn: 'מחק',
      deleteConfirm: 'האם אתה בטוח שברצונך למחוק מתכון זה?',
      deleteError: 'שגיאה במחיקת המתכון',
      editModalTitle: 'עריכת מתכון',
      saveBtn: 'שמור שינויים',
      saving: 'שומר...',
      cancelBtn: 'ביטול',
      updateSuccess: 'המתכון עודכן בהצלחה',
      updateError: 'שגיאה בעדכון המתכון',
      noRecipes: 'לא נמצאו מתכונים',
    },
    nutritionist: {
      title: 'דשבורד תזונאי',
      nameLabel: 'שם המתכון',
      namePlaceholder: 'לדוגמה: סלמון בגריל',
      mealTypeLabel: 'סוג ארוחה',
      mealTypePlaceholder: 'בחר סוג ארוחה...',
      mealTypes: { breakfast: 'ארוחת בוקר', lunch: 'ארוחת צהריים', dinner: 'ארוחת ערב' },
      caloriesLabel: 'קלוריות (קק"ל)',
      caloriesPlaceholder: 'לדוגמה: 450',
      proteinLabel: "חלבון (ג')",
      proteinPlaceholder: 'לדוגמה: 35',
      carbsLabel: "פחמימות (ג')",
      carbsPlaceholder: 'לדוגמה: 40',
      fatLabel: "שומן (ג')",
      fatPlaceholder: 'לדוגמה: 12',
      descriptionLabel: 'תיאור המתכון',
      descriptionPlaceholder: 'לדוגמה: מנה בריאה ועשירה בטעם...',
      allergensLabel: 'אלרגנים',
      isVegetarianLabel: '🌱 מתכון צמחוני',
      ingredientsLabel: 'מצרכים',
      ingredientsPlaceholder: 'לדוגמה: 200 גרם חזה עוף, 1 כף שמן זית...',
      ingredientsHint: 'הפרד כל מצרך בפסיק. לציון כמות, כתוב: שם (כמות).',
      instructionsLabel: 'הוראות הכנה',
      instructionsPlaceholder: 'לדוגמה: 1. חמם מחבת.\n2. צלה את העוף 5 דקות מכל צד.',
      instructionsHint: 'שלב אחד בכל שורה.',
      submit: 'הוסף מתכון',
      submitting: 'שומר...',
      success: 'המתכון נוסף בהצלחה!',
      errName: 'שם המתכון הוא שדה חובה.',
      errMealType: 'יש לבחור סוג ארוחה.',
      errCalories: 'יש להזין מספר קלוריות גדול מ-0.',
      errProtein: 'חלבון חייב להיות 0 או יותר.',
      errCarbs: 'פחמימות חייבות להיות 0 או יותר.',
      errFat: 'שומן חייב להיות 0 או יותר.',
      errServer: 'שגיאה ביצירת המתכון.',
    },
  },
  en: {
    dir: 'ltr',
    navbar: {
      brand: '🥗 Smart Nutrition System',
      dashboard: 'Dashboard',
      recipeManagement: 'Recipe Management',
      settings: 'Settings',
      hello: 'Hello',
      logout: 'Logout',
    },
    footer: {
      name: 'Smart Nutrition Planning System',
      year: '2026',
      slogan: 'Eat right, live well',
    },
    login: {
      title: 'Smart Nutrition System',
      subtitle: 'Sign in or Register — one simple form',
      registerNote: "New user? Enter any email and password and we'll build your personal nutrition profile",
      emailLabel: 'Email',
      emailPlaceholder: 'your@email.com',
      passwordLabel: 'Password',
      passwordPlaceholder: 'At least 6 characters',
      submit: 'Sign In / Register',
      loading: 'Signing in...',
      hint: 'Example: maya@example.com / 123456',
      errEmail: 'A valid email address is required',
      errPassword: 'Password must be at least 6 characters',
      errWrongPassword: 'Incorrect password',
    },
    dashboard: {
      qTitle: "Let's build your personal menu",
      qSubtitle: 'Fill in your personal details to get a customized daily menu',
      ageLabel: 'Age',
      weightLabel: 'Weight (kg)',
      heightLabel: 'Height (cm)',
      goalLabel: 'Goal',
      goals: { loss: 'Weight Loss', gain: 'Muscle Gain', health: 'Healthy Living' },
      activityLabel: 'Activity Level',
      activityLevels: {
        sedentary: 'Sedentary (little/no exercise)',
        light: 'Light (1–3 days/week)',
        moderate: 'Moderate (3–5 days/week)',
        active: 'Active (6–7 days/week)',
        very_active: 'Very Active (physical job)',
      },
      allergiesTitle: 'Allergies',
      allergiesSubtitle: 'Check all that apply',
      allergens: {
        eggs: 'Eggs', dairy: 'Dairy', gluten: 'Gluten',
        fish: 'Fish', nuts: 'Nuts', soy: 'Soy',
      },
      preferencesTitle: 'Dietary Preferences',
      vegetarianOnly: 'Vegetarian only',
      submit: 'Create Daily Menu ➤',
      menuTitle: 'Your Daily Menu',
      caloriesInfo: 'Calorie Target',
      calories: 'calories',
      recalc: 'Recalculate',
      saveMenu: 'Save Menu',
      menuSaved: 'Menu saved!',
      tableTitle: 'Recipes Suitable for You',
      loading: 'Loading recipes...',
      fetchError: 'Error loading recipes from server',
      noRecipes: 'No suitable recipes found',
      noRecipeForMeal: 'No suitable recipe found for this meal based on your preferences',
      profileAllergies: 'Allergies',
      profilePrefs: 'Preferences',
      none: 'None',
      menuError: 'No matching menu found. Try adjusting your settings.',
      errAge: 'Age must be between 10 and 120',
      errWeight: 'Weight must be between 20 and 300 kg',
      errHeight: 'Height must be between 100 and 250 cm',
    },
    table: {
      name: 'Recipe Name',
      mealType: 'Meal',
      calories: 'Calories',
      protein: 'Protein (g)',
      carbs: 'Carbs (g)',
      fat: 'Fat (g)',
      vegetarian: 'Vegetarian',
      mealTypes: { breakfast: 'Breakfast', lunch: 'Lunch', dinner: 'Dinner' },
      empty: 'No data to display',
      swapLabel: 'Swap',
      currentMeal: '✓ Current',
      swapTo: { breakfast: 'Use for Breakfast', lunch: 'Use for Lunch', dinner: 'Use for Dinner' },
    },
    card: {
      mealTypes: { breakfast: 'Breakfast', lunch: 'Lunch', dinner: 'Dinner' },
      veg: '🌱 Vegetarian',
      calories: 'Calories',
      protein: 'Protein',
      carbs: 'Carbs',
      fat: 'Fat',
      prepTime: 'Prep time',
      prepUnit: 'min',
    },
    modal: {
      ingredients: 'Ingredients',
      instructions: 'Preparation Instructions',
      close: 'Close',
      prepTime: 'Prep time',
      prepUnit: 'min',
      calories: 'Calories',
      protein: 'Protein',
      carbs: 'Carbs',
      fat: 'Fat',
      veg: '🌱 Vegetarian',
      allergens: 'Allergens',
    },
    settings: {
      title: 'Settings',
      firstNameLabel: 'First Name',
      lastNameLabel: 'Last Name',
      languageLabel: 'Language',
      notificationsLabel: 'Receive email notifications',
      save: 'Save Changes',
      saving: 'Saving...',
      success: 'Settings saved successfully',
      errLoad: 'Error loading settings',
      errSave: 'Error saving settings',
      errFirstName: 'First name is required',
      loading: 'Loading settings...',
      langHe: 'עברית',
      langEn: 'English',
      accountTitle: 'Account Details',
      emailLabel: 'Email',
      newPasswordLabel: 'New Password',
      newPasswordPlaceholder: 'Leave blank to keep current password',
      confirmPasswordLabel: 'Confirm Password',
      saveAccount: 'Update Account',
      savingAccount: 'Updating...',
      accountSuccess: 'Account details updated successfully',
      errEmail: 'A valid email address is required',
      errPassword: 'Password must be at least 6 characters',
      errPasswordMatch: 'Passwords do not match',
      errAccountSave: 'Error updating account details',
    },
    admin: {
      title: 'Admin Dashboard',
      loading: 'Loading users…',
      colId: '#',
      colName: 'Name',
      colEmail: 'Email',
      colRole: 'Role',
      colActions: 'Actions',
      deleteBtn: 'Delete',
      youBadge: 'You',
      roles: { user: 'User', nutritionist: 'Nutritionist', admin: 'Admin' },
      errLoad: 'Failed to load users.',
      errUpdate: 'Failed to update role.',
      errDelete: 'Failed to delete user.',
    },
    recipeManagement: {
      title: 'Recipe Management',
      loading: 'Loading recipes...',
      fetchError: 'Error loading recipes',
      colName: 'Recipe Name',
      colMealType: 'Meal Type',
      colCalories: 'Calories',
      colProtein: 'Protein (g)',
      colCarbs: 'Carbs (g)',
      colFat: 'Fat (g)',
      colActions: 'Actions',
      editBtn: 'Edit',
      deleteBtn: 'Delete',
      deleteConfirm: 'Are you sure you want to delete this recipe?',
      deleteError: 'Failed to delete recipe',
      editModalTitle: 'Edit Recipe',
      saveBtn: 'Save Changes',
      saving: 'Saving...',
      cancelBtn: 'Cancel',
      updateSuccess: 'Recipe updated successfully',
      updateError: 'Failed to update recipe',
      noRecipes: 'No recipes found',
    },
    nutritionist: {
      title: 'Nutritionist Dashboard',
      nameLabel: 'Recipe Name',
      namePlaceholder: 'e.g. Grilled Salmon',
      mealTypeLabel: 'Meal Type',
      mealTypePlaceholder: 'Select meal type…',
      mealTypes: { breakfast: 'Breakfast', lunch: 'Lunch', dinner: 'Dinner' },
      caloriesLabel: 'Calories (kcal)',
      caloriesPlaceholder: 'e.g. 450',
      proteinLabel: 'Protein (g)',
      proteinPlaceholder: 'e.g. 35',
      carbsLabel: 'Carbs (g)',
      carbsPlaceholder: 'e.g. 40',
      fatLabel: 'Fat (g)',
      fatPlaceholder: 'e.g. 12',
      descriptionLabel: 'Recipe Description',
      descriptionPlaceholder: 'e.g. A healthy and flavourful dish...',
      allergensLabel: 'Allergens',
      isVegetarianLabel: '🌱 Vegetarian recipe',
      ingredientsLabel: 'Ingredients',
      ingredientsPlaceholder: 'e.g., 200g Chicken breast, 1 tbsp Olive oil...',
      ingredientsHint: 'Separate each ingredient with a comma. To add an amount, write: name (amount).',
      instructionsLabel: 'Instructions',
      instructionsPlaceholder: 'e.g., 1. Heat the pan.\n2. Grill the chicken for 5 minutes each side.',
      instructionsHint: 'One step per line.',
      submit: 'Add Recipe',
      submitting: 'Saving…',
      success: 'Recipe created successfully!',
      errName: 'Recipe name is required.',
      errMealType: 'Please select a meal type.',
      errCalories: 'Calories must be greater than 0.',
      errProtein: 'Protein must be 0 or more.',
      errCarbs: 'Carbs must be 0 or more.',
      errFat: 'Fat must be 0 or more.',
      errServer: 'Failed to create recipe.',
    },
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const saved = localStorage.getItem('language') || 'he';
  const [lang, setLang] = useState(saved);

  function switchLanguage(newLang) {
    localStorage.setItem('language', newLang);
    setLang(newLang);
  }

  const t = translations[lang] || translations.he;

  return (
    <LanguageContext.Provider value={{ lang, switchLanguage, t }}>
      <div dir={t.dir}>{children}</div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
